baseURL = "https://ja.ngs.io/"
defaultContentLanguage = "ja"
ignoreLogs = ['warning-goldmark-raw-html']
languageCode = "ja"
title = "長瀬 敦史"

[module]
[[module.imports]]
path = "go.ngs.io/hugo-primer-blog"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[params]
author = "長瀬 敦史"
defaultTheme = "auto"
description = "長瀬 敦史のブログ"
faviconPng = "favicon.png"
googleAnalyticsID = "G-VM0QRV63E8"
primaryColor = "#f67717ff"
showAuthor = true
showReadingTime = true

[[params.appleTouchIcons]]
href = "apple-touch-icon-152x152-precomposed.png"
sizes = "152x152"
[[params.appleTouchIcons]]
href = "apple-touch-icon-144x144-precomposed.png"
sizes = "144x144"
[[params.appleTouchIcons]]
href = "apple-touch-icon-120x120-precomposed.png"
sizes = "120x120"
[[params.appleTouchIcons]]
href = "apple-touch-icon-114x114-precomposed.png"
sizes = "114x114"
[[params.appleTouchIcons]]
href = "apple-touch-icon-76x76-precomposed.png"
sizes = "76x76"
[[params.appleTouchIcons]]
href = "apple-touch-icon-72x72-precomposed.png"
sizes = "72x72"
[[params.appleTouchIcons]]
href = "apple-touch-icon-60x60-precomposed.png"
sizes = "60x60"
[[params.appleTouchIcons]]
href = "apple-touch-icon-precomposed.png"

[[params.sidebarModules]]
partial = "links"

[[params.sidebarModules]]
partial = "recentPosts"

[[params.sidebarModules]]
partial = "archive"

[[params.sidebarModules]]
partial = "tags"

[params.social]
bluesky = "ngs.io"
github = "ngs"
x = "ngs"

[permalinks]
posts = "/:year/:month/:day/:slug/"

[taxonomies]
archive = "archives"
tag = "tags"

[[menus.main]]
name = "ホーム"
pageRef = "/"
weight = 10

[[menus.main]]
name = "自己紹介"
pageRef = "/about"
weight = 20

[[menus.main]]
name = "Blog (English)"
url = "https://ngs.io/"
weight = 30
